### ISSUE TITLE
Ruby catalog of my things

### ISSUE THREAD

**Issue by Mre55** [Mre55/Ruby-Catalog-of-my-things#38]
[Link to the GitHub project Kanban board](https://github.com/Mre55/Ruby-Catalog-of-my-things/projects/2)

We have a team of three:

- Team member 1: @Mre55 
- Team member 2: @TheLuisAbarca 
- Team member 3: @keroloussamy

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
